/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

/**
 *
 * @author Hmmm1
 */

import Controlador.Controlador;
import Dados.Departamento;
import javax.swing.table.DefaultTableModel;

public class Buscar_departamentos extends javax.swing.JDialog {
    protected DefaultTableModel model;
    /**
     * Creates new form Buscar
     */
    public Buscar_departamentos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencher_valor.setVisible(false);
        String colunas[]={"Código","Nome","Gatos"};
        model = new DefaultTableModel(colunas,0);
        Tabela_dep.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_dep = new javax.swing.JTable();
        btn_mostrar_departamentos = new javax.swing.JButton();
        buscar_departamento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buscar_valor = new javax.swing.JTextField();
        preencher_valor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Buscar Departamentos");

        Tabela_dep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabela_dep);

        btn_mostrar_departamentos.setText("Geral");
        btn_mostrar_departamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrar_departamentosActionPerformed(evt);
            }
        });

        buscar_departamento.setText("Buscar");
        buscar_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_departamentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Gastos:");

        preencher_valor.setForeground(new java.awt.Color(255, 0, 0));
        preencher_valor.setText("Preencha com um valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btn_mostrar_departamentos)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar_valor, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar_departamento)
                .addGap(29, 29, 29)
                .addComponent(preencher_valor)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mostrar_departamentos)
                    .addComponent(buscar_departamento)
                    .addComponent(jLabel2)
                    .addComponent(buscar_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preencher_valor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrar_departamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrar_departamentosActionPerformed
        Departamento[] dep=Controlador.universidade.exibir_departamento();
        if(model.getRowCount()!=0){
            for(int i=0;i<dep.length;i++){
                model.removeRow(0);
            }
            for(int i=0;i<dep.length;i++){
                if(dep[i]!=null){
                  Object[] valores={dep[i].exibir_cod(),dep[i].exibir_nome(),dep[i].exibir_gastos()};
                  model.addRow(valores);  
                }
            }
        }
        else{
            for(int i=0;i<dep.length;i++){
                if(dep[i]!=null){
                  Object[] valores={dep[i].exibir_cod(),dep[i].exibir_nome(),dep[i].exibir_gastos()};
                  model.addRow(valores);    
                }
            }
        } 
    }//GEN-LAST:event_btn_mostrar_departamentosActionPerformed

    private void buscar_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_departamentoActionPerformed
        if(buscar_valor.getText().equals("")){
            preencher_valor.setVisible(true);
        }
        else{
            Departamento[] dep=Controlador.universidade.buscar_departamento_valor(Double.parseDouble(buscar_valor.getText()));
            if(model.getRowCount()!=0){
                for(int i=0;i<dep.length;i++){
                    model.removeRow(0);
                }
                for(int i=0;i<dep.length;i++){
                    if(dep[i]!=null){
                      Object[] valores={dep[i].exibir_cod(),dep[i].exibir_nome(),dep[i].exibir_gastos()};
                      model.addRow(valores);  
                    }
                }
            }
            else{
                for(int i=0;i<dep.length;i++){
                    if(dep[i]!=null){
                      Object[] valores={dep[i].exibir_cod(),dep[i].exibir_nome(),dep[i].exibir_gastos()};
                      model.addRow(valores);    
                    }
                }
            } 
                preencher_valor.setVisible(false);
        }
        
    }//GEN-LAST:event_buscar_departamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar_departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar_departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar_departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar_departamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Buscar_departamentos dialog = new Buscar_departamentos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela_dep;
    private javax.swing.JButton btn_mostrar_departamentos;
    private javax.swing.JButton buscar_departamento;
    private javax.swing.JTextField buscar_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel preencher_valor;
    // End of variables declaration//GEN-END:variables
}
