/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Controlador.Controlador;
import Dados.Departamento;
import Dados.Efetivo;
import Dados.Substituto;
import javax.swing.JOptionPane;

/**
 *
 * @author Hmmm1
 */
public class Cadastrar_docente extends javax.swing.JDialog {

    /**
     * Creates new form Cadastrar_docente
     */
    public Cadastrar_docente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        c_departamento.removeAllItems();
        Departamento departamentos[]=Controlador.universidade.exibir_departamento();
        for (Departamento departamento : departamentos) {
            if (departamento != null) {
                c_departamento.addItem(departamento.exibir_nome());
            }
        }
        prof_igual.setVisible(false);
        p_efetivo.setVisible(false);
        p_substituto.setVisible(false);
        sucesso.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        n_docente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        s_docente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sa_docente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        c_titulação = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        c_departamento = new javax.swing.JComboBox<>();
        r_efetivo = new javax.swing.JRadioButton();
        r_substituto = new javax.swing.JRadioButton();
        p_efetivo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        c_area = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        c_nivelefetivo = new javax.swing.JComboBox<>();
        p_substituto = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_choraria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        c_nivelsub = new javax.swing.JComboBox<>();
        sucesso = new javax.swing.JLabel();
        prof_igual = new javax.swing.JLabel();
        btn_cadastrar_docente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Cadastro de Novo Docente");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nome:");

        n_docente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Sobrenome:");

        s_docente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Salário:");

        sa_docente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Titulação:");

        c_titulação.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_titulação.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Graduação", "Mestrado", "Doutorado", "Livre-Docência", "Titular" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Departamento:");

        c_departamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_departamentoActionPerformed(evt);
            }
        });

        r_efetivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_efetivo.setText("Efetivo");
        r_efetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_efetivoActionPerformed(evt);
            }
        });

        r_substituto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        r_substituto.setText("Susbtituto");
        r_substituto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_substitutoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Área:");

        c_area.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_area.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biológicas", "Exatas", "Humanas", "Saúde" }));
        c_area.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nivel");

        c_nivelefetivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_nivelefetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D1", "D2", "D3" }));
        c_nivelefetivo.setToolTipText("");
        c_nivelefetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nivelefetivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_efetivoLayout = new javax.swing.GroupLayout(p_efetivo);
        p_efetivo.setLayout(p_efetivoLayout);
        p_efetivoLayout.setHorizontalGroup(
            p_efetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_efetivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_nivelefetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_efetivoLayout.setVerticalGroup(
            p_efetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_efetivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_efetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_efetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(c_nivelefetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_efetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(c_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Carga horária:");

        c_choraria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_choraria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "24" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nivel");

        c_nivelsub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        c_nivelsub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1", "S2" }));
        c_nivelsub.setToolTipText("");
        c_nivelsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nivelsubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_substitutoLayout = new javax.swing.GroupLayout(p_substituto);
        p_substituto.setLayout(p_substitutoLayout);
        p_substitutoLayout.setHorizontalGroup(
            p_substitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_substitutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_choraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_nivelsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        p_substitutoLayout.setVerticalGroup(
            p_substitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_substitutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_substitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_substitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(c_nivelsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_substitutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(c_choraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sucesso.setForeground(new java.awt.Color(51, 204, 0));
        sucesso.setText("Cadastrado com sucesso");

        prof_igual.setForeground(new java.awt.Color(255, 0, 0));
        prof_igual.setText("Esse funcionário ja foi cadastrado");

        btn_cadastrar_docente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cadastrar_docente.setText("Cadastrar");
        btn_cadastrar_docente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_docenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(n_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sa_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_titulação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(r_efetivo)
                                .addComponent(r_substituto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btn_cadastrar_docente)
                                    .addGap(289, 289, 289))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(prof_igual)
                                    .addGap(252, 252, 252))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(108, 108, 108)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(p_efetivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(p_substituto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sucesso)
                        .addGap(272, 272, 272))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(n_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(sa_docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(c_departamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(c_titulação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p_efetivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r_efetivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_substituto)))
                .addComponent(p_substituto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(sucesso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prof_igual)
                .addGap(18, 18, 18)
                .addComponent(btn_cadastrar_docente)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_departamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_departamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_departamentoActionPerformed

    private void r_efetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_efetivoActionPerformed
        r_substituto.setSelected(false);
        p_efetivo.setVisible(true);
        p_substituto.setVisible(false);
    }//GEN-LAST:event_r_efetivoActionPerformed

    private void r_substitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_substitutoActionPerformed
        r_efetivo.setSelected(false);
        p_substituto.setVisible(true);
        p_efetivo.setVisible(false);
    }//GEN-LAST:event_r_substitutoActionPerformed

    private void c_nivelefetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nivelefetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nivelefetivoActionPerformed

    private void c_nivelsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nivelsubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nivelsubActionPerformed

    private void btn_cadastrar_docenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_docenteActionPerformed
        if(r_efetivo.isSelected()){
            if(n_docente.getText().equals("") || s_docente.getText().equals("") ||
                sa_docente.getText().equals("")){
                prof_igual.setText("Preencha todos os campos!");
                prof_igual.setVisible(true);
            }
            else{
                Efetivo efetivo;
                Double salario = Double.parseDouble(sa_docente.getText());
                efetivo = new Efetivo(n_docente.getText()+" "+s_docente.getText(),salario,
                    c_nivelefetivo.getSelectedItem().toString(),c_titulação.getSelectedItem().toString(),
                    c_area.getSelectedItem().toString());
                efetivo.calcularSalario(c_nivelefetivo.getSelectedItem().toString());
                if(Controlador.cadastrar_docente_efetivo(Controlador.buscar_departamento(c_departamento.getSelectedItem().toString()),
                    efetivo)){
                n_docente.setText("");
                s_docente.setText("");
                sa_docente.setText("");
                sucesso.setVisible(true);
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso", "Cadastrado concluido", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else if(r_substituto.isSelected()){
            if(n_docente.getText().equals("") || s_docente.getText().equals("") ||
                sa_docente.getText().equals("")){
                prof_igual.setText("Preencha todos os campos!");
                prof_igual.setVisible(true);
            }
            else{
                Substituto sub;
                Double salario = Double.parseDouble(sa_docente.getText());
                int carga_horaria=Integer.parseInt(c_choraria.getSelectedItem().toString());
                sub = new Substituto(n_docente.getText()+" "+s_docente.getText(),salario,
                    c_nivelsub.getSelectedItem().toString(),c_titulação.getSelectedItem().toString(),
                    carga_horaria);
                sub.calcularSalario(c_nivelsub.getSelectedItem().toString());
                if(Controlador.cadastrar_docente_substituto(Controlador.buscar_departamento(c_departamento.getSelectedItem().toString()),
                    sub)){
                n_docente.setText("");
                s_docente.setText("");
                sa_docente.setText("");
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso", "Cadastrado concluido", JOptionPane.WARNING_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar", "Algo deu errado", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_cadastrar_docenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar_docente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastrar_docente dialog = new Cadastrar_docente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar_docente;
    private javax.swing.JComboBox<String> c_area;
    private javax.swing.JComboBox<String> c_choraria;
    private javax.swing.JComboBox<String> c_departamento;
    private javax.swing.JComboBox<String> c_nivelefetivo;
    private javax.swing.JComboBox<String> c_nivelsub;
    private javax.swing.JComboBox<String> c_titulação;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n_docente;
    private javax.swing.JPanel p_efetivo;
    private javax.swing.JPanel p_substituto;
    private javax.swing.JLabel prof_igual;
    private javax.swing.JRadioButton r_efetivo;
    private javax.swing.JRadioButton r_substituto;
    private javax.swing.JTextField s_docente;
    private javax.swing.JTextField sa_docente;
    private javax.swing.JLabel sucesso;
    // End of variables declaration//GEN-END:variables
}
