/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import java.awt.Color;
import Controlador.Controlador;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Hmmm1
 */
public class Inicio extends javax.swing.JDialog {

    /**
     * Creates new form Inicio
     */
    public Inicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        obrigatorio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        luniversidade = new javax.swing.JLabel();
        nome_universidade = new javax.swing.JTextField();
        ldepartamento = new javax.swing.JLabel();
        nome_departamento1 = new javax.swing.JTextField();
        nome_departamento2 = new javax.swing.JTextField();
        a2 = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        obrigatorio = new javax.swing.JLabel();

        luniversidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        luniversidade.setText("Nome da Universidade : *");

        nome_universidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ldepartamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ldepartamento.setText("Nome do Departamento : *");

        nome_departamento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome_departamento1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_departamento1FocusLost(evt);
            }
        });

        nome_departamento2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome_departamento2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nome_departamento2FocusLost(evt);
            }
        });

        a2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        a2.setText("Nome do Departamento: ");

        btn_iniciar.setText("Iniciar");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        obrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        obrigatorio.setText("Preencha os campos obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(luniversidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nome_universidade))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(a2)
                                    .addComponent(ldepartamento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome_departamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nome_departamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_iniciar)
                                .addGap(149, 149, 149))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(obrigatorio)
                                .addGap(91, 91, 91))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luniversidade)
                    .addComponent(nome_universidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldepartamento)
                    .addComponent(nome_departamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a2)
                    .addComponent(nome_departamento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(obrigatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_iniciar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        if(nome_universidade.getText().isEmpty() || nome_departamento1.getText().isEmpty()){
            luniversidade.setForeground(Color.red);
            ldepartamento.setForeground(Color.red);
            obrigatorio.setText("Preencha os campos obrigatórios!");
           obrigatorio.setVisible(true);
        }
        else{
            if(nome_departamento1.getText().equals(nome_departamento2.getText())){
                obrigatorio.setText("Departamentos devem ter nomes únicos!");
                obrigatorio.setVisible(true);
            }
            else{
                if(Controlador.inicializar(nome_universidade.getText(),nome_departamento1.getText(),
                            nome_departamento2.getText())){
                    nome_universidade.setText("");
                    nome_departamento1.setText("");
                    nome_departamento2.setText("");
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso", "Cadastrado concluido", JOptionPane.WARNING_MESSAGE);
                    Controlador.fecharDialog(this);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Algo deu errado", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void nome_departamento1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_departamento1FocusLost
        if(nome_departamento1.getText().equals(nome_departamento2.getText())){
            obrigatorio.setText("Departamentos devem ter nomes únicos!");
        }
    }//GEN-LAST:event_nome_departamento1FocusLost

    private void nome_departamento2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nome_departamento2FocusLost
        if(nome_departamento2.getText().equals(nome_departamento1.getText())){
            obrigatorio.setText("Departamentos devem ter nomes únicos!");
        }
    }//GEN-LAST:event_nome_departamento2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio dialog = new Inicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a2;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JLabel ldepartamento;
    private javax.swing.JLabel luniversidade;
    private javax.swing.JTextField nome_departamento1;
    private javax.swing.JTextField nome_departamento2;
    private javax.swing.JTextField nome_universidade;
    private javax.swing.JLabel obrigatorio;
    // End of variables declaration//GEN-END:variables
}
